### ISSUE TITLE
Some packages install binaries in `[...]/bin/x86_64-linux/x86_64-linux`

### ISSUE THREAD

**Issue by gabrielbdsantos** [Fbrisset/asdf-tinytex#5]
**Describe the bug**

When installing packages via `tlmgr`, some binaries are placed in `[...]/bin/x86_64-linux/x86_64-linux`.

**Steps to reproduce**

For example, install the `glossaries` package and then try to find it using `which`.

```bash
tlmgr install glossaries
which makeglossaries
```

**Expected behavior**

Binaries should be placed under `[...]/bin` or `[...]/bin/x86_64-linux`.

**Additional context**

It seems that during the installation processes, the plugin uses symlink to redirect `[...]/bin -> [...]/binaries/x86_64-linux`. This strategy creates a loophole, where new packages are then placed in `[...]/bin/x86_64-linux/x86_64-linux`. Perhaps, a better strategy would be using a [`bin/list-bin-path`](https://asdf-vm.com/plugins/create.html#bin-list-bin-paths) script to list the different paths where binaries can be found.

I have already made a patch that fixes this issue using the `bin/list-bin-path` approach. If you wish, I can submit a pull request.

**Comment by Fbrisset** [comment]
All right. You can submit your modifications, I will look when I have a little more time

**Comment by gabrielbdsantos** [comment]
Ok. I'll do it later this week.

**Comment by Fbrisset** [comment]
Your solution is merged and thanks !
